ALTER TABLE users
  ADD COLUMN IF NOT EXISTS last_login_at  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS login_count    INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_seen_at   TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS app_opens      INT NOT NULL DEFAULT 0;
